#!/bin/bash

# replaygain-flac - A convenience script to add ReplaiGain data to flac files.

# Written in 2021 by Matthew Nakayama matthewnakayama@gmail.com

# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.

# You should have received a copy of the CC0 Public Domain Dedication along with
# this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

# Based on the guide by Bobulous.
# <https://www.bobulous.org.uk/misc/Replay-Gain-in-Linux.html#flac-and-metaflac>.


# usage: replaygain-flac [files]
# Requires metaflac to be installed. This binary should be included with the
# official flac package in your distribution.


set -e

function add-meta {
    metaflac --add-replay-gain "$@"
    metaflac --list "$@" | grep REPLAYGAIN
}

if [ "$#" -lt 1 ]; then
    # by default, add to all flac files in folder
    add-meta *.flac
else
    add-meta "$@"
fi
